services:
  - type: web
    name: pos-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: COOKIE_SECURE
        value: true
      - key: CLIENT_URL
        sync: false
      - key: STORE_NAME
        value: POS Retail Store
